polls/polls/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls_app.urls')),
    path('', include('polls_app.urls')),
]

polls/polls_app/urls.py
from django.urls import path
from . import views


app_name = 'polls_app'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/polls_app/models.py
from django.db import models
from django.utils import timezone

import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/polls_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question as qs, Choice as ch


class IndexView(generic.ListView):
    template_name = 'polls_app/home.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions(
        not including those to be published in the future).
        """

        return qs.objects.filter(
            pub_date__lte=timezone.now()
        )


class DetailView(generic.DetailView):
    model = qs
    template_name = 'polls_app/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return qs.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = qs
    template_name = 'polls_app/result.html'


def vote(request, question_id):
    question = get_object_or_404(qs, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, ch.DoesNotExist):
        return render(request, 'polls_app/detail.html', {
            'question': question,
            'err_msg': 'You didn\'t select a choice'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls_app:results', args=(question.id,)))

polls/polls_app/templates/polls_app/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
    <h2>{{ question.question_text }}</h2>

    {% if err_msg %} <p><strong style="color:red;">{{ err_msg }}</strong></p> {% endif %}

    <form action="{% url 'polls_app:vote' question.id %}" method="post">{% csrf_token %}

        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice-{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice-{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br>
        {% endfor %}
        <br>
        <button type="submit" value="Vote">Vote</button>
        <hr>
    </form>

</body>
</html>

polls/polls_app/templates/polls_app/home.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'polls_app/style.css'%}">
    <title>Home</title>
</head>
<body>
    <h1>IT WORKS! -> {{ q_id }}</h1>

    {% if latest_question_list %}
        <ul>
            {% for q in latest_question_list %}
            <li><a href="{% url 'polls_app:detail' q.id %}">{{ q.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h4>No polls are available.</h4>
    {% endif%}

</body>
</html>

polls/polls_app/templates/polls_app/result.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Result</title>
</head>
<body>
    <h2>{{ question.question_text }}</h2>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
</body>
</html>

polls/polls_app/templates/polls_app/vote.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Vote</title>
</head>
<body>

</body>
</html>